### PR TITLE
Cogs reorganization

### PR DESCRIPTION
**Pull request by harrisj**
This is a work in progress on reorganizing the project to follow a cogs structure and separate models. It is not ready to be merged.

Supported commands:

- !luck _luck_points_ = rolls under a luck and tells success or failure
- !spell _skill_ = rolls under a spell skill and reports success/failure (handles Oops!)
- !oops = if you want to call the oops table directly
- !attack _attacker-skill_ _defender-skill_ = does a roll versus for attacks. Handles all the critical blow and fumble rules
- !damage weapon-name armor [roll_modifier] = rolls for damage and looks it up in the weapon table
- Initiative group:
  - !init begin (starts a battle)
  - !init add 3 Goblin 4 Ogre... (adds tokens to the bag)
  - !init remove 2 Ogre (removes tokens from the bag)
  - !init round (shuffles the bag and starts a round of battle, draws first token)
  - !init draw (draws a token)
  - !init delay Goblin = returns a token to the round bag and reshuffles
  - !init current = shows current token
  - !init end = ends battle and reports a summary (need to check on this one)
 

**UPDATE**: I have rebased this to be merged after #11. Merge that first

### CODE REVIEW

**Comment by harrisj** [comment]
So, I got it working to test Initiative and Weapon damage in Discord. But I would like to clean things up more, but I think that would maybe make sense to put in a future PR. Main plans:

1. Adapt Avrae's mock http approach for testing cog interactions
2. Simplify the argument processing for armor in weapon damage
3. Switch to using the d20 library so I can annotate rolls + bonuses in weapons and elsewhere
4. Fix the initiative tracker to support creatures with spaces in their names

**Comment by harrisj** [comment]
This is ready for review. It also works if you add your Discord token to a .env and run it

```
!oops
d66 (63): A different, random Spell goes off, directed at the same target.
!w damage large beast light +1
ROLL 1d6 (1) -1 [light armor] +1 [ignore armor] +1 [damage roll bonus] = 2 DAMAGE=6
!i begin
Battle started. Now add tokens with init add...
!i add 4 goblin 2 ogre 1 hero
!i round
Starting round 1 of combat! Shuffling the bag...
Current Turn: Ogre
!i draw
Current Turn: Goblin
```

A few other things to clean up (want to make the args processing for tokens support tokens with spaces in them, etc.) as well as adding tests, but it's getting there. Also need to add combat

**Comment by harrisj** [comment]
@natehole I'm done now. Will need to add some more tests, but let me know. I am sorry it's such a big PR, but I got carried away

**Comment by natehole** [comment]
Awesome! I'll check it out tonight or tomorrow night.

**Comment by natehole** [comment]
I haven't finished and have only started. I'll keep reviewing the code over the rest of the week.
I've checked out the changes to bot.py and the general layout of the cogs and models. So far everything looks really good.

I haven't really dug in deep yet. The only critique I have so far is nitpicky and minor. 
In the initiative cog, the remove method doesn't support "!remove token" or another way to purge all tokens. However, I might get further into reviewing that and see there is an easy way to do just that. 

The remove method will also take negative numbers and return the statement. It works how it is and would return something like the following:
"Removed -1 out of 2 Dwarf tokens in the bag"

Also!
If you would like for me to merge changes into master and review after I am fine with that too. This looks great and is much grander and cleaner than anything I would have done.

**Comment by harrisj** [comment]
Sure, I can merge too. I thought I did have a remove token operation, but let me know if I am missing that

**Pull request merged**
